# basic options
title: Dolika. Портфолио
author: Михаил Черноскутов
email: mikhail.chernoskutov@gmail.cm
description: Мои добрые дела ©2018
github_username:  mikhailche
show_downloads: false

logo: imgs/logo.png

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
