# basic options
title: Dolika. Портфолио
author: Михаил Черноскутов
email: mikhail.chernoskutov@gmail.cm
description: Мои добрые дела
github_username:  mikhailche

# Build settings
markdown: kramdown
theme: minima